# Inferno Cop Configuration File

# Illegal regexes
illegal_regexes:
  next: "Next ((monday)|(tuesday)|(wednesday)|(thursday)|(friday)|(saturday)|(sunday))"
  washington_football_team: "redskins"
  curse: "((fuck)|(shit)|(bitch)|(arse)|(ass)|(bastard)|(cunt)|(damn)|(retard)|(cock)|(dick)|(balls)|(piss)|(crap)|(cum)|(cuck)|(douche)|(felching)|(whore)|(jizz)|(pussy)|(slut)|(tits)|(titties)|(wank))"