# Inferno Cop Configuration File

# Illegal regexes
illegal_regexes:
  next: "Next ((monday)|(tuesday)|(wednesday)|(thursday)|(friday)|(saturday)|(sunday))"
  washington_football_team: "redskins"
  g_word: "gamer"